main.yml

diff --git a/DevOps-Project/Portfolio-code/.github/workflows/main.yml b/DevOps-Project/Portfolio-code/.github/workflows/main.yml
--- a/DevOps-Project/Portfolio-code/.github/workflows/main.yml
+++ b/DevOps-Project/Portfolio-code/.github/workflows/main.yml
@@ -15,9 +15,9 @@ jobs:
 
     - name: Validate Files Exist
       run: |
-        test -f DevOps-Project/Dummy-portfolio-code/index.html || (echo "index.html missing" && exit 1)
-        test -f DevOps-Project/Dummy-portfolio-code/style.css || (echo "style.css missing" && exit 1)
-        test -f DevOps-Project/Dummy-portfolio-code/script.js || (echo "script.js missing" && exit 1)
+        test -f DevOps-Project/Portfolio-code/index.html || (echo "index.html missing" && exit 1)
+        test -f DevOps-Project/Portfolio-code/style.css || (echo "style.css missing" && exit 1)
+        test -f DevOps-Project/Portfolio-code/script.js || (echo "script.js missing" && exit 1)
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
@@ -28,4 +28,5 @@ jobs:
 
     - name: Deploy to S3
       run: |
-        aws s3 sync DevOps-Project/Dummy-portfolio-code/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+        aws s3 sync DevOps-Project/Portfolio-code/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+
